update linux support to indicate python 3.4
learningequality/kolibri-docs pull request #12
Opened 2018-04-04 15:31 UTC by indirectlylit

re: https://github.com/learningequality/kolibri-installer-debian/issues/25

currently we indicate that python 2.7 is supported, but it's not

2018-04-04 15:34 UTC, benjaoming requested changes
Python 2 and 3 are both supported on linux. It's a matter of which the Debian is built for, e.g. it installs to `/usr/lib/python3.5/dist-packages`

2018-04-04 15:34 UTC, benjaoming commented on docs/install/_system_requirements.rst
> + - Linux: Any system with Python 3.4
It should say "Any system with Python 2.7 and 3.4+". The issue is that the Debian installer is only built for Python3, which in any case is available on the systems listed above.

2018-04-04 17:59 UTC, indirectlylit commented
Okay, so is it this line that needs to be updated, e.g.:

> - Debian/Ubuntu with Python 3.4: 14.04, 16.04 and up - anything that's *not* end-of-life.

2018-04-04 23:04 UTC, benjaoming commented
@indirectlylit yes, that would be more accurate. I think the problem with Tim's installation is that he doesn't want Python 3.5 on the system and has removed it completely, so with `dpkg -i` the missing dependency isn't installed but instead causes a halt (because `dpkg` does not install dependencies).

2018-04-07 19:55 UTC, indirectlylit commented
closing. after looking at the docs, I think we need a bit more work than just this change. new issue coming.

2018-04-07 19:55 UTC, closed without merging