Updated repositories for debian
learningequality/kolibri-docs pull request #160
Opened 2020-03-12 03:36 UTC by privateseabass

Cosmic was the old ubuntu repository.
to obtain kolibri-server, users need to install the current (bionic) repositories.

2020-03-12 15:51 UTC, benjaoming requested changes
THANKS! That was a due change!

2020-03-12 15:51 UTC, benjaoming commented on docs/install/ubuntu-debian.rst
> +    sudo su -c 'echo "deb http://ppa.launchpad.net/learningequality/kolibri/ubuntu bionic main" > /etc/apt/sources.list.d/learningequality-ubuntu-kolibri-cosmic.list'
```suggestion
    sudo su -c 'echo "deb http://ppa.launchpad.net/learningequality/kolibri/ubuntu bionic main" > /etc/apt/sources.list.d/learningequality-ubuntu-kolibri.list'
```

Removing "cosmic", but also not replacing it with another dist name will ensure that re-applying instructions later in time won't duplicate repos.

2020-03-12 17:03 UTC, benjaoming approved these changes

2020-03-12 17:05 UTC, merged

2020-03-13 13:53 UTC, radinamatic commented
Thank you @privateseabass! 👍