Static IP address troubleshooting
learningequality/kolibri-docs pull request #65
Opened 2019-02-17 16:39 UTC by benjaoming

This is a subject that's hard to cover, but I feel like we need to add some words about it, since it's been a recent subject of support questions.

2019-02-19 06:15 UTC, radinamatic commented on docs/manage/_get_support.rst
> +Therefor, you should be cautious that when such a router or access point restarts (for instance during a power cut), it may forget the IP address assigned to your Kolibri device, and thus the IP chan
Missing _*e*_ in `Therefor`.

2019-02-19 06:20 UTC, radinamatic commented
Just a bit confused about the included files: you reference `_troubleshooting.rst`, but all the newly added content is still in the `_get_support.rst` and does not get included once the docs are built... :confused: 

Is one of those two files meant to be deleted?

2019-02-19 12:23 UTC, radinamatic requested changes
Check what you are using the `include` directive for!

2019-02-20 15:22 UTC, indirectlylit submitted a review, later dismissed

2019-02-20 15:22 UTC, indirectlylit commented on docs/manage/_get_support.rst
> +.. _troubleshooting:
your updates regarding static IPs are not showing up - looks like you may have started refactoring page names but didn't finish?

There is now content that's duplicated between this file (`_get_support.rst`) and the newly-created `_troubleshooting.rst`

2019-02-20 15:23 UTC, indirectlylit commented on docs/manage/_get_support.rst
> +.. _troubleshooting:
whoops sorry - didn't see @radinamatic's review. I'll close mine

2019-02-20 15:25 UTC, indirectlylit commented
these updates look great overall.

Made some minor suggestions here: https://github.com/benjaoming/kolibri-docs/pull/1

2019-03-12 21:41 UTC, benjaoming commented
Sorry about the confusion, yes it was indeed an artifact that should not have been in the PR. It's fixed now.

2019-03-25 07:42 UTC, radinamatic approved these changes

2019-03-25 09:56 UTC, merged