Update user docs for 0.12 release
learningequality/kolibri-docs pull request #67
Opened 2019-03-08 06:50 UTC by radinamatic

- [X]  Update all the new UI and feature changes for the Coach dashboard

- [X]  Replace `Exams` for `Quizzes`

- [X]  Update version number 0.11 to 0.12 in installer filenames

- [X]  Explicitly add iOS Safari 9.3+ to the list of supported browsers. Documents [#4676](https://github.com/learningequality/kolibri/pull/4676).

- [X]  Update Device > Info and Facility > Data pages

- [X]  Update all the screenshots with the new appbar

- [X]  Management commands for reordering channels. Documents [#4799](https://github.com/learningequality/kolibri/pull/4799).

- [X]  Clarify command line instructions. Fixes #66

2019-03-11 20:53 UTC, benjaoming requested changes
Wow - so many changes :) Would maybe have liked some smaller PRs before the big push leading up to a release. But let's totally fast track all these positive changes! I have one big concern, and that's if this would be a good time to implement proper version string substitution and get rid of all the hard-coded version strings.

2019-03-11 20:53 UTC, benjaoming commented on docs/install/_linux.rst
> +#. Download the latest `.deb installer <https://learningequality.org/download/>`_ for Kolibri **version 0.12**, or have it copied to your local drive.
Could possibly leave out the version number here for possible merge conflicts and future maintenance.

2019-03-11 20:53 UTC, benjaoming commented on docs/install/_linux.rst
> +#. Download the latest `.deb installer <https://learningequality.org/download/>`_ for Kolibri **version 0.12**, or have it copied to your local drive.
Otherwise, we could make a substitution pattern.

2019-03-11 20:53 UTC, benjaoming commented on docs/learn.rst
> +Quiz that you did not yet submit will be marked with the |in-progress| icon, so you can easily recognize it, and click to resume when you are ready.
```suggestion
A Quiz that you did not yet submit will be marked with the |in-progress| icon, so you can easily recognize it, and click to resume when you are ready.
```

2019-03-11 20:53 UTC, benjaoming commented on docs/manage/_advanced.rst
> +* On macOS open Spotlight and type ``Terminal``. You may also need to prefix the commands with ``python -m``, for example ``python -m kolibri start``.
Is "open Spotlight" a good instruction?

2019-03-11 20:53 UTC, benjaoming commented on docs/manage/_advanced.rst
> +* In Windows you need to open ``cmd.exe`` Command prompt (for example with the :guilabel:`WIN` + :guilabel:`R` shortcut) in the folder where Kolibri executable is located (most probably ``C:/Python34
I'm pretty sure that `WIN+R` + `type "cmd"` is a universal instruction.

2019-03-11 20:53 UTC, benjaoming commented on docs/manage/_advanced.rst
> +* If you are running Kolibri with the ``PEX`` file, make sure to substitute the ``kolibri`` in below commands **with the exact name of the file you downloaded** preceded by ``./``. For example, to st
Adding more hard-coded version strings seems problematic.

2019-03-11 21:07 UTC, indirectlylit approved these changes
looks great!

no blocking requests here, but a bunch of small notes

2019-03-11 21:07 UTC, indirectlylit commented on docs/_static/theme_overrides.css
> +    /*background-color: #fff;*/
it's common practice to delete commented-out code before committing it

2019-03-11 21:07 UTC, indirectlylit commented on docs/coach.rst
> +Click on a class to access the progress-tracking features and create lessons, quizzes and groups.
do we generally use serial/oxford commas?

2019-03-11 21:07 UTC, indirectlylit commented on docs/coach.rst
> +-------
I wonder if it's helpful to add a note that in previous versions, quizzes were called exams?

2019-03-11 21:07 UTC, indirectlylit commented on docs/coach.rst
> +* You can click on the progress bar itself to open the complete quiz data in the **Reports** tab.
the word 'itself' seems perhaps unnecessary (same on L44)

2019-03-11 21:07 UTC, indirectlylit commented on docs/coach.rst
> +As learners interact with lessons and quizzes, you can track their progress in the **Class activity** block in real time.
super minor note feel free to ignore:

it might be worth thinking of alternative ways of saying "in real time" because...

* it's not truly real-time - there can be up to a 30-second lag
* the phrase "in real time" might not translate easily?

2019-03-11 21:07 UTC, indirectlylit commented on docs/coach.rst
> +* When learners input an incorrect answer to a question in a quiz or a lesson, the notification in the **Class activity** block will display that one or more learners need help |need-help| with a spe
> When learners input an incorrect answer to a question in a quiz or a lesson

two notes:

* 'needs help' notifications only occur for exercises in lessons. They do not appear for quizzes
* maybe rephrase to "When learners input multiple incorrect answers..."

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_advanced.rst
> +Tips for Working from the Command Line
header seems a bit redundant with the one above it

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_advanced.rst
> +* If you are running Kolibri with the ``PEX`` file, make sure to substitute the ``kolibri`` in below commands **with the exact name of the file you downloaded** preceded by ``./``. For example, to st
>  with the `PEX` file

maybe 

> with the `.pex` file

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_advanced.rst
> +* Make sure not to include the angle brackets “< >” in the commands below.
Maybe

> In the commands below, angle brackets and the text between them (`<...>`) are used to denote placeholders for you to modify. Make sure to replace them with your own information.

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_groups.rst
> +Enroll Learners in Group
would add 'a':

> Enroll Learners in **a** Group

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_groups.rst
> +    * List in this view contains all the learners currently **NOT** enrolled in the selected group.
maybe lower-case 'not'? seems like it's yelling at me :)

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_quizzes.rst
> +You can view, create and delete quizzes, as well as assign them to learners, using the **Quizzes** sub-tab in the **Plan** tab (|edit| icon) of your **Coach** dashboard. Default view displays the lis
> **The** default view displays the list of all quizzes...

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_quizzes.rst
> +  You can filter the search results by *type* of resource (exercise or topic), include only those from a specific *channel*, or exclude :ref:`resources for coaches <coach_resource>`. Click :guilabel:
this item and the one above it are kind of the same category of action: browsing the topic tree and searching in order to add a content

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_quizzes.rst
> +   * To present the questions in a different (*random*) order to each learner, select :guilabel:`Randomized`. You can not change the order of questions established by the quiz builder, but you can cl
I'd recommend giving the 'Choose a different set of questions' function its own description, separate from the randomized vs fixed toggle:

* 'choose different questions' is something that helps the coach select questions to display
* fixed vs random affects how learners interact with the selected questions

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_quizzes.rst
> +To create a new quiz |exams|, follow these steps.
The list below is presented as an ordered sequence of actions, but the new UI is designed such that the user can actually perform them in any order. For example, you might select some content, go to preview, choose how many questions you want, go back to select more content, go forward and set a name, and then change question order

I think it would be preferable to de-emphasize the idea that they need to perform the steps in a specific order

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_quizzes.rst
> +Once you set the visibility of quiz to the chosen group(s) of learners, you need to **Activate** it so it can appear in the **Learn** view of the learners it is assigned to.
might want to explicitly say that quizzes are not active by default. This still trips me up sometimes

2019-03-11 21:07 UTC, indirectlylit commented on docs/manage/_quizzes.rst
> +If the quiz is copied to another group in the same class, it will appear in the **Quizzes** tab as the *Copy of...*. Follow the steps in the next heading to rename it.
> in the next heading

to 

> in the next section

2019-03-11 23:08 UTC, indirectlylit commented
> I have one big concern, and that's if this would be a good time to implement proper version string substitution and get rid of all the hard-coded version strings.

@benjaoming I agree with this idea, but maybe it would be better to open a new issue for it?

2019-03-11 23:28 UTC, radinamatic commented
@benjaoming Please, do file an issue to change the hardcoded strings, and I'll address them next week after the conference, together with all the notes by @indirectlylit. 

If there's no major gaffe or stuff missing in this PR, let's merge it so it's ready for the blog announcement tomorrow.

2019-03-12 00:54 UTC, benjaoming commented
Yes, I can see you 2 pair-programming that feature :) thanks for responding!

2019-03-12 00:55 UTC, benjaoming approved these changes

2019-03-12 18:13 UTC, merged