update the doc for the new log file locations
learningequality/kolibri-docs pull request #96
Opened 2019-05-22 16:47 UTC by lyw07

This is related to the new kolibri log files.
PR: https://github.com/learningequality/kolibri/pull/5495

Please feel free to comment if the wording doesn't make sense or more information is needed. Thank you so much!

2019-05-22 19:51 UTC, benjaoming reviewed
Looking good, just 2 suggestions

2019-05-22 19:51 UTC, benjaoming commented on docs/manage/_troubleshooting.rst
> +Open the ``.kolibri`` folder inside the :ref:`Home <home>` folder of the device where Kolibri is running and locate the ``logs`` folder. You will be able to find these two files:
```suggestion
Open the ``.kolibri/`` folder inside the :ref:`Home <home>` folder of the Kolibri server and locate the ``logs/`` folder. You will be able to find these two files:
```

2019-05-22 19:51 UTC, benjaoming commented on docs/manage/_troubleshooting.rst
> +If the problem happened at a certain date, you can open the ``archive`` folder under the ``logs`` folder to find the specific log file:
```suggestion
If the problem happened earlier than the dates in the above log, you can open the ``archive/`` folder inside ``logs/`` to find older log files:
```

2019-05-22 19:52 UTC, lyw07 commented on docs/manage/_troubleshooting.rst
> +Open the ``.kolibri`` folder inside the :ref:`Home <home>` folder of the device where Kolibri is running and locate the ``logs`` folder. You will be able to find these two files:
wow this is cool github feature! thank you for the suggestions!

2019-05-22 19:55 UTC, benjaoming commented on docs/manage/_troubleshooting.rst
> +Open the ``.kolibri`` folder inside the :ref:`Home <home>` folder of the device where Kolibri is running and locate the ``logs`` folder. You will be able to find these two files:
Yeah, it's nice -- I try to only use it for documentation and the likes, since it's a bit more tricky for code and syntax stuff :)

2019-05-22 23:00 UTC, radinamatic requested changes
Doc changes look good, but if this feature is going into `0.12.y` branch on Kolibri, this PR should be targeting the `release-v0.12.x` branch of the docs.

2019-05-22 23:01 UTC, lyw07 commented
@radinamatic I don't see the troubleshooting page in 0.12.x branch. Do you know where will be the best place to put this information? Thank you!

2019-05-22 23:14 UTC, radinamatic commented
@lyw07 Try here :slightly_smiling_face: 

https://github.com/learningequality/kolibri-docs/blob/release-v0.12.x/docs/manage/_get_support.rst#locate-kolibri-log-files

2019-05-22 23:18 UTC, lyw07 commented
oh thank you! I will create a new PR for the 0.12.x branch

2019-06-09 05:33 UTC, radinamatic commented
Superseded by #97

2019-06-09 05:33 UTC, closed without merging